name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    # - name: List build files
    #   run: ls -alh ./dist

    # - name: Sync to S3
    #   run: aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete --exclude "node_modules/*"
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: ${{ secrets.AWS_REGION }}
    #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #     ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
    #     NODE_ENV: ${{ secrets.NODE_ENV }}
    #     PORT: ${{ secrets.PORT }}
    #     REACT_APP_SERVICE_ID: ${{secrets.REACT_APP_SERVICE_ID}}
    #     REACT_APP_TEMPLATE_ID: ${{secrets.REACT_APP_TEMPLATE_ID}}
    #     REACT_APP_USER_ID: ${{secrets.REACT_APP_USER_ID}}
        
